#!/bin/sh
# Unix interface wrapper for `service-core`, but actually handles halt/reboot as well
WD=/var/service-core

. `realpath "$SERVICE_CORE_DIR/config"` || exit 1

CMD=
CORE_PID_FILE="$SERVICE_CORE_DIR/state/pid"
PID=`cat "$CORE_PID_FILE"`

if [ ! $? ] || [ -z "$PID" ]
then
  echo "No \`service-core\` instance detected."
  exit
fi

case $1
in
  0)
    CMD=halt
    ;;
  6)
    CMD=reboot
    ;;
  *)
    echo "Expected 0 or 6." >&2
    exit 1
esac

kill -s TERM "$PID"
echo -n "Waiting for \`service-core\` to terminate..."

while [ -e "$PID_FILE" ]
do
  sleep "$SLEEP"
done
echo "done."
"$CMD" -f

