#!/bin/sh
# Unix interface wrapper for `service-core`, but actually handles halt/reboot as well
SERVICE_CORE_DIR=/var/service-core
CMD=
CONFIG_DIR="$SERVICE_CORE_DIR/config"
PID_FILE="$SERVICE_CORE_DIR/state/pid"
PID=`cat "$PID_FILE"`
SLEEP=`cat $CONFIG_DIR/sleep`

if [ $? != "0" ]
then
  # use default value

  SLEEP=1
fi

case $1
in
  0)
    CMD=halt
    ;;
  6)
    CMD=reboot
    ;;
  *)
    echo "Expected 0 or 6." >&2
    exit 1
esac

kill -s TERM "$PID"
echo -n "Waiting for \`service-core\` to terminate..."

while [ -e "$PID_FILE" ]
do
  sleep "$SLEEP"
done
echo "done."
"$CMD" -f

